name: GitHub Pages

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.110.0'
          extended: true

      - name: SetUp Env
        run: hugo new site testenv

      - name: Set theme
        uses: actions/checkout@v3
        with:
          path: ./testenv/themes/hugo-theme-shell

      - name: Build
        run: hugo --minify -t hugo-theme-shell
        working-directory: ./testenv

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./testenv/public
